Repository AY2425S2-CS2103T-T09-2/tp, pull requests merged in 2025-04, with the labels that each got.

#131 Add comfirm box
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/ui/ConfirmWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/warning.png
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/ConfirmWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.Low

#132 Fix marking unmarking appointment shift order
  src/main/java/seedu/address/model/Klinix.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/AppointmentListByDate.java
Labels: type.Bug, alpha-bug

#137 Fix Appointment Panel does not reflect existing appointments with matching date
  src/main/java/seedu/address/model/Klinix.java
Labels: type.Bug, alpha-bug

#133 Update developer guide UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
Labels: priority.High

#142 Add exceptions and tests for appointments overlapping
  src/main/java/seedu/address/commons/util/AppointmentConflictFormatter.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/AppointmentListByDate.java
  src/main/java/seedu/address/model/appointment/exceptions/OverlappingAppointmentException.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentListTest.java
  src/test/java/seedu/address/ui/TestPersonListPanel.java
Labels: priority.High

#155 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#159 Fix issue where inputs in various commands can be set to an invalid date
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/parser/AddMedicineUsageCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewAppointmentByDateParser.java
  src/test/java/seedu/address/logic/parser/AddMedicineUsageCommandParserTest.java
Labels: severity.Low, alpha-bug

#158 Fix issue where birthday can be set to a date in the future
  src/main/java/seedu/address/model/person/BirthDate.java
Labels: severity.Low, alpha-bug

#157 Improve parsing for AddAppointmentCommandParser
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
Labels: type.Enhancement, priority.High

#160 Fix incorrect unmark appointment message after successful execution of unmark appointment command
  src/main/java/seedu/address/logic/commands/UnmarkAppointmentVisitedCommand.java
Labels: severity.Low, alpha-bug

#166 Add MedicineName and Dosage class
  src/main/java/seedu/address/logic/parser/AddMedicineUsageCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicineusage/Dosage.java
  src/main/java/seedu/address/model/medicineusage/MedicineName.java
  src/main/java/seedu/address/model/medicineusage/MedicineUsage.java
  src/main/java/seedu/address/model/person/MedicineUsageContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedMedicineUsage.java
  src/test/java/seedu/address/logic/commands/AddMedicineUsageCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearMedicineUsageCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMedicineUsageCommandTest.java
  src/test/java/seedu/address/logic/parser/AddMedicineUsageCommandParserTest.java
  src/test/java/seedu/address/logic/parser/KlinixParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/medicineusage/MedicineUsageListTest.java
  src/test/java/seedu/address/model/medicineusage/MedicineUsageTest.java
  src/test/java/seedu/address/model/person/MedicineUsageContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedicineUsageTest.java
  src/test/java/seedu/address/ui/TestPersonListPanel.java
Labels: alpha-bug

#156 Fix input bugs
  src/main/java/seedu/address/logic/parser/AddMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedicalReport.java
  src/test/java/seedu/address/logic/parser/AddMedicalReportCommandParserTest.java
Labels: alpha-bug

#169 Fix Ui inconsistencies
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: severity.Low, alpha-bug

#170 Better date handle for add medicine usage
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/parser/AddMedicineUsageCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/BirthDate.java
  src/test/java/seedu/address/ui/TestPersonListPanel.java
Labels: alpha-bug

#179 Update DeveloperGuide.md for manual testing for Appointment commands
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
Labels: priority.High, severity.Low

#173 Fix UG
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#178 Fix use cases
  docs/DeveloperGuide.md
Labels: severity.Low, alpha-bug

#175 Update date formats in documentation and code to use dd-MM-yyyy format
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/appointment/AppointmentListByDate.java
  src/main/java/seedu/address/model/person/BirthDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddMedicineUsageCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearMedicineUsageCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ViewappointmentByDateParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentListTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/person/BirthDateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/TestPersonListPanel.java
Labels: alpha-bug

#177 Add medicine usages in sample persons
  src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java
  src/main/java/seedu/address/model/medicineusage/MedicineUsage.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#180 Stricter medicine name equality
  src/main/java/seedu/address/logic/commands/AddMedicineUsageCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/medicineusage/MedicineName.java
  src/main/java/seedu/address/model/medicineusage/MedicineUsage.java
  src/main/java/seedu/address/model/person/BirthDate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#185 Update dg manual testing for medicalreport
  docs/DeveloperGuide.md
Labels: priority.Medium

#183 Revise Quick Start instructions for clarity and organization in UG
  docs/UserGuide.md
Labels: alpha-bug

#184 Fix error message in view appointment
  src/main/java/seedu/address/logic/commands/ViewAppointmentByDateCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAppointmentByDateCommandTest.java
Labels: severity.Medium, alpha-bug

#187 Add table of parameters to UG
  docs/UserGuide.md
Labels: severity.Medium, alpha-bug

#192 Add instructions for manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/Extensions.css
Labels: alpha-bug

#196 Add appointments to sample data in SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.High, alpha-bug

#197 Fix bugs and standardize output messages
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Nric.java
Labels: severity.High, alpha-bug

#204 Fix AddAppoinmentCommand bug
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
Labels: severity.High, alpha-bug

#200 Update `clearmu` functionality
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java
  src/main/java/seedu/address/logic/parser/ClearMedicineUsageCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearMedicineUsageCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearMedicineUsageCommandParserTest.java
Labels: priority.Medium

#211 Add index functionality to `deletemr` `delete` and `clearappt`
  src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMedicalReportCommand.java
  src/main/java/seedu/address/logic/parser/ClearAppointmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/ClearMedicineUsageCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteMedicalReportCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearAppointmentsCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearAppointmentsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteMedicalReportCommandParserTest.java
Labels: priority.High

#214 Fix output messages
  src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMedicalReportCommand.java
Labels: priority.Medium, severity.Low

#217 Update UserGuide.md and fix Name constraints
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: priority.High, severity.Low

#218 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ClearMedicineUsageCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteMedicineUsageCommandParser.java
  src/main/java/seedu/address/logic/parser/FindMedicineUsageCommandParser.java
Labels: priority.High

#296 Update links to diagrams in DeveloperGuide.md and add new sections
  docs/DeveloperGuide.md
Labels: priority.High

#222 Refactor CSS styles for improved dark theme consistency and button aesthetics
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Low

#297 Fix bug for Appointments and Medical Usage list being shared
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/person/MedicalReport.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/TestPersonListPanel.java
Labels: priority.High, severity.Medium

#303 Update user guide command summary for add command
  docs/UserGuide.md
Labels: alpha-bug

#302 fix: remove space in example usage of delete medicine command
  src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java
Labels: alpha-bug

#308 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium

#301 Catch all exceptions in CommandBox to improve error handling
  src/main/java/seedu/address/ui/CommandBox.java
Labels: alpha-bug

#306 Add mouse click event to update result display in PersonListPanel
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: alpha-bug

#311 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#312 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#314 Update UserGuide.md and fix spacing in date error message
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/DateUtil.java
Labels: priority.Medium

#304 Fix bugs
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindMedicineUsageCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicineusage/MedicineName.java
  src/main/java/seedu/address/model/person/MedicineUsageContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug

#327 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#330 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#335 Update DeveloperGuide.md and update messages
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java
Labels: priority.High

#360 Update UserGuide.md
  docs/UserGuide.md
  docs/images/Klinix_logo.png
Labels: priority.High

#363 Update UserGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: priority.Medium

#364 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#375 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#377 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#378 Add Klinix logo to DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium

#381 Update link for diagrams for DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#382 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium

#386 Fix typo in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Bug, severity.Low

#390 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Medium
